name: Add, commit, and push
description: ✨ Automagically git add, git commit, and git push

branding:
  icon: git-commit
  color: blue

inputs:
  path:
    description: >
      The path to the repository root folder to perform the Git operations in.
      This defaults to the current working directory ('.'). Change this to a
      subfolder if you are using a different folder other than the default
      'github.workspace' for your Git repository.
    default: .
  add-pathspec:
    description: >
      Additional path specifiers to be passed to 'git add'. These can be files,
      folders, globs, or even some fancy Git pathspec things such as
      ':!ignoreme.txt'. Check out the CSS-Tricks Git Pathspecs and How to Use
      Them article for the highlights of Git pathspecs. If this input is not
      specified, 'git add --all' will be used instead. Specifying '.' has
      slightly different behaviour from '--all'.
  add-force:
    description: >
      Whether or not to use the '--force' flag when performing the 'git add'
      operation. Use this if you really want to add something but it's in your
      '.gitignore'. This can be useful if you ever need to commit build
      artifacts to Git that are normally ignored by your '.gitignore'. Defaults
      to 'false'.
    default: false
  commit-author:
    description: ""
  commit-author-name:
    description: >
      The name of the author to associate with the commit. Should be left
      unspecified if 'commit-author' is specified.
  commit-author-email:
    description: >
      The email address of the author to associate with the commit. Should be
      left unspecified if 'commit-author' is specified.
  commit-committer:
    description: ""
  commit-committer-name:
    description: >
      The name of the committer to associate with the commit. Should be left
      unspecified if 'commit-committer' is specified.
  commit-committer-email:
    description: >
      The email address of the committer to associate with the commit. Should be
      left unspecified if 'commit-committer' is specified.
  commit-message:
    description: >
      The '--message' parameter to use for the commit. This can be a multiline
      string if you want to specify a title and body. The default is 'Automated
      changes'.
    default: Automated changes
  push-repository:
    default: origin
  push-refspec: {}
  push-force:
    default: false

outputs:
  committed:
    description: >
      Whether or not anything was actually committed to the repository locally.
      This will be 'true' if there were any changes and 'false' if not.
  commit-sha:
    description: >
      The SHA of the commit that was created. Will not be set if nothing was
      committed.
  pushed:
    description: >
      Whether or not anything was actually pushed to the remote repository. This
      will be 'true' if there were any changes that were pushed and 'false' if
      not.

runs:
  using: node20
  main: _main.mjs
