name: Add, commit, and push
description: ✨ Automagically git add, git commit, and git push

branding:
  icon: git-commit
  color: blue

inputs:
  path:
    description: >
      The path to the repository root folder to perform the Git operations in.
      This defaults to the current working directory ('.'). Change this to a
      subfolder if you are using a different folder other than the default
      'github.workspace' for your Git repository.
    default: .
  add-pathspec:
    description: >
      Additional path specifiers to be passed to 'git add'. These can be files,
      folders, globs, or even some fancy Git pathspec things such as
      ':!ignoreme.txt'. Check out the CSS-Tricks Git Pathspecs and How to Use
      Them article for the highlights of Git pathspecs. If this input is not
      specified, 'git add --all' will be used instead. Specifying '.' has
      slightly different behaviour from '--all'.
  add-force:
    description: >
      Whether or not to use the '--force' flag when performing the 'git add'
      operation. Use this if you really want to add something but it's in your
      '.gitignore'. This can be useful if you ever need to commit build
      artifacts to Git that are normally ignored by your '.gitignore'. Defaults
      to 'false'.
    default: false
  commit-author:
    description: >
      A 'Name Here <emailhere@example.org>' AiO author name & email string. This
      is a shortcut alternative to the independant 'commit-author-name' and
      'commit-author-email' options that are also available. This defaults to
      @github-actions[bot]. You can set this to the special value
      'github-actions' to use the @github-actions[bot] user as the author, or
      the special 'me' value to use the current 'github.actor' user as the
      author. Note that this is different from the 'commit-committer'. The
      author of a commit is who wrote the thing and the committer is who
      committed it to Git. It's recommended to leave this as the default.
    default: github-actions[bot]
  commit-author-name:
    description: >
      The name of the author to associate with the commit. Should be left
      unspecified if 'commit-author' is specified.
  commit-author-email:
    description: >
      The email address of the author to associate with the commit. Should be
      left unspecified if 'commit-author' is specified.
  commit-committer:
    description: >
      A 'Name Here <emailhere@example.org>' AiO author name & email string. This
      input is a shortcut for the 'commit-committer-name' and
      'commit-committer-email' inputs that can also be individually specified.
      You can set this to the special value 'github-actions' to use the
      @github-actions[bot] user as the committer, or the special 'me' value to
      use the current 'github.actor' user as the committer. If this input is
      unspecified, the committer defaults to the author.
  commit-committer-name:
    description: >
      The name of the committer to associate with the commit. Should be left
      unspecified if 'commit-committer' is specified.
  commit-committer-email:
    description: >
      The email address of the committer to associate with the commit. Should be
      left unspecified if 'commit-committer' is specified.
  commit-message:
    description: >
      The '--message' parameter to use for the commit. This can be a multiline
      string if you want to specify a title and body. The default is 'Automated
      changes'.
    default: Automated changes
  push-repository:
    description: >
      The first argument to 'git push [repository] [refspec]'. You can change
      this to another remote name like 'upstream' (as long as you have push
      rights) or another Git remote entirely like
      'https://github.com/octocat/another-repo.git'. The default 'origin' is
      probably what you want.
    default: origin
  push-refspec:
    description: >
      A specific branch or tag name to push to. If this is a tag, 'push-force'
      will default to 'true' unless explicitly set otherwise. Defaults to
      whatever the current Git 'HEAD' target is.
  push-force:
    description: >
      Whether or not to use the '--force' parameter when doing the 'git push'.
      You may need to specify this if you are rewriting history or editing a
      tag. Defaults to 'false' if the 'push-refspec' is a branch and 'true' if
      it's a tag.

outputs:
  # commit-sha: {}

# https://github.com/jcbhmr/configure-bun-action
runs:
  using: bun1
  # main: out/main.js
  main: src/main.ts
