name: Add, commit, and push
description: ✨ Automagically git add, git commit, and git push

branding:
  icon: git-commit
  color: blue

inputs:
  path:
    default: .
  add-path:
    default: .
  add-force:
    default: false
  commit-author:
    default: |
      ${{ github.actor }} ${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com
  commit-author-name:
  commit-author-email:
  commit-committer:
    default: |
      github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
  commit-committer-name:
  commit-committer-email:
  commit-message:
    default: Automatic commit
  push-force:
    default: false

outputs:
  commit-sha:

# https://github.com/jcbhmr/configure-bun-action
runs:
  using: bun1
  main: out/main.js
