name: publish-action
on:
  release:
    types: released
concurrency: ${{ github.workflow }}
jobs:
  publish-action:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun run build
      - uses: jcbhmr/configure-bun-action@v0.5.0
      # - uses: actions4git/add-commit-push@v1
      #   with:
      #     add-force: true
      - run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
      - run: git add -Af && git commit -m 'Automatic changes'
      - run: git tag -f "$TAG" && git push -f origin "$TAG"
        env:
          TAG: ${{ github.event.release.tag_name }}
      - uses: actions/publish-action@v0.2.2
        with:
          source-tag: ${{ github.event.release.tag_name }}
